In [ ]:
#有一个非常大的数组比如1亿个数字，求出里面数字小于5000的数字数目
import numpy as np
c=np.random.randint(1,10000,size=(10**8))#或size=int(1e8)
print((c<5000).sum())

In [1]:
#如何在数组A中找到满足包含B中元素的行？(不考虑B中每行元素顺序)？(提示: np.where)
import numpy as np
a=np.random.choice(3,(8,3))
b=np.random.choice(3,(2,2))
for ia in range(8):
    e=np.array(a[ia])
    mmp=np.in1d(b,e)
    mmp1=mmp.all()
    print(e,b,mmp,mmp1)
    d=(np.where(mmp1,ia,None))
    print(d)

[2 2 2] [[0 2]
 [0 0]] [False  True False False] False
None
[0 2 1] [[0 2]
 [0 0]] [ True  True  True  True] True
1
[2 1 1] [[0 2]
 [0 0]] [False  True False False] False
None
[0 2 1] [[0 2]
 [0 0]] [ True  True  True  True] True
3
[2 2 0] [[0 2]
 [0 0]] [ True  True  True  True] True
4
[1 0 2] [[0 2]
 [0 0]] [ True  True  True  True] True
5
[1 0 0] [[0 2]
 [0 0]] [ True False  True  True] False
None
[2 0 2] [[0 2]
 [0 0]] [ True  True  True  True] True
7
